import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`w-full h-[100vh] overflow-hidden bg-gradient-to-r from-gray-200 via-gray-400 to-gray-600`}>
        <Hero />
      </main>
    </div>
  )
}
